# Generated by Django 6.0.2 on 2026-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmark_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image_url',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='file_url',
            new_name='file',
        ),
    ]
